# Generated by Django 5.0 on 2023-12-12 10:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('kpi_views', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('chart_views', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('default', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('month_no', models.IntegerField()),
                ('quarter', models.CharField(max_length=200)),
                ('year_month', models.CharField(max_length=200)),
                ('month_name', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=200)),
                ('week_ending_mon_sun_dt', models.CharField(max_length=200)),
                ('min_orderdatetime', models.CharField(max_length=200)),
                ('kpi', models.CharField(max_length=200)),
                ('menu_category', models.CharField(max_length=200)),
                ('menu_group', models.CharField(max_length=200)),
                ('menu_item', models.CharField(max_length=200)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_starttime', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_endtime', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['createdAt'],
            },
        ),
    ]
