# Generated by Django 4.1 on 2022-11-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='chart_views',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='kpi_views',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_endtime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_starttime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
