# Generated by Django 4.1 on 2022-11-23 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_plan_chart_views_plan_default_plan_kpi_views_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'get_latest_by': ['createdAt']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
