# Generated by Django 4.1 on 2022-12-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_subscription_options_subscription_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('month_no', models.IntegerField(default=0)),
                ('quarter', models.CharField(max_length=200)),
                ('year_month', models.CharField(max_length=200)),
                ('month_name', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=200)),
                ('week_ending_mon_sun_dt', models.DateTimeField(max_length=200)),
                ('min_orderdatetime', models.DateTimeField(max_length=200)),
                ('kpi', models.CharField(max_length=200)),
                ('menu_category', models.CharField(max_length=200)),
                ('menu_group', models.CharField(max_length=200)),
                ('menu_item', models.CharField(max_length=200)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
