# Generated by Django 4.1 on 2022-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_dummydata_min_orderdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummydata',
            name='min_orderdatetime',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dummydata',
            name='week_ending_mon_sun_dt',
            field=models.CharField(max_length=200),
        ),
    ]
