# Generated by Django 4.1 on 2022-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dummydata_min_orderdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummydata',
            name='month_no',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
