# Generated by Django 4.1 on 2022-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_dummydata_month_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummydata',
            name='month_no',
            field=models.IntegerField(),
        ),
    ]
